exclude: ^kaggle_IML/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace # Remove trailing whitespace
      - id: end-of-file-fixer # Ensure files end with a newline
      - id: check-yaml # Check yaml files for parseable syntax
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout # Strip output from Jupyter notebooks
        files: ".ipynb"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      # Lint Python files with ruff, fixing issues automatically, fail commit if any issues were fixed,
      # use repo's pyproject.toml for configuration
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --config=connect_4_RL/pyproject.toml]
      - id: ruff-format # Format Python files with ruff
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.407
    hooks:
      - id: pyright # Type check Python files with pyright
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.15.0
    hooks:
      - id: pretty-format-toml # Format TOML files with pretty-format-toml
        args: [--autofix]
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt # Format YAML files with yamlfmt
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
