name: pre-commit
on:
  push:
    branches: [main]
  pull_request:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Check out the repository with the 4th version of the checkout action
      - uses: actions/setup-python@v5
        with:
          python-version-file: "connect_4_RL/.python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Create venv and install dependencies
        run: uv sync --project connect_4_RL
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
        working-directory: connect_4_RL
      - name: Run pyright
        run: uv run --project connect_4_RL pyright
        working-directory: connect_4_RL
